spring.application.name=code
spring.datasource.url=jdbc:postgresql://localhost:5433/transactions_db
spring.datasource.username=morca
spring.datasource.password=morca
spring.datasource.driver-class-name=org.postgresql.Driver

# validate = hibernate checks entities match the db
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=morca
spring.rabbitmq.password=morca


webhook.notifications-url=https://webhook.site/3d7f734f-96b5-4a3b-9347-fa66f8e84fed